version: "3"

networks:
  backend:

services:
  app:
    build: ./app
    restart: always
    expose:
      - "8080"
    env_file:
      - common.env
    networks:
      backend:
        aliases:
          - app.petandbe.com
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev:/etc/nginx/conf.d
    networks:
      backend:
    depends_on:
      - app
  
  db:
    image: mysql:8.0
    restart: always
    expose:
      - "3306"
    env_file:
      - common.env
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      backend:
        aliases:
          - db.petandbe.com
  redis:
    image: redis:7.0.7
    restart: always
    expose:
      - 6379
    volumes:
      - "./redis:/data"
    networks:
      backend:
        aliases:
          - redis.petandbe.com