version: "3"

networks:
  backend:

services:
  app:
    build: ./app
    restart: always
    expose:
      - "8080"
    env_file:
      - common.env
    networks:
      backend:
        aliases:
          - app.petandbe.com
    depends_on:
      - db

  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/staging:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      backend:
    depends_on:
      - app
      - db
  
  db:
    image: mysql:8.0
    restart: always
    expose:
      - "3306"
    env_file:
      - common.env
    networks:
      backend:
        aliases:
          - db.petandbe.com
