spring:
  secret:
    business-authenticity:
      url: "http://api.odcloud.kr/api/nts-businessman/v1/validate?serviceKey="
      service-key: "SDknnRn8ZJSaepNdwIW7WeV5ZUqyNaK31vkjERfM7Lwi%2F9xJ8ArunrvWB0PYzHQJz5rawN8U4eADXTDXOzZoSg%3D%3D"