#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/petandbe"
#    username: dev
#    password: dev
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    database: mysql
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
spring:
  application:
    name: programmers spring assignments
#  profiles:
#    include: oauth, db
#    active: test
  messages:
    basename: i18n/messages, errors
    encoding: UTF-8
    cache-duration: PT1H
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

